gems:
  - octopress-linkblog
  # - octopress-include-tag
  - octopress-littlefoot
  - octopress-solarized
  - octopress-gist
  # - octopress-codefence

# Site settings
title: kaushik gopal's blog
email: iam@kaush.co
description: > # this means to ignore newlines until "baseurl:"
  Curated thoughts on various topics like programming, technology, music, life and personal stuff from Kaushik Gopal.
  Friends call me kaush.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.kaush.co" # the base hostname & protocol for your site
twitter_username: kaushikgopal
github_username:  kaushikgopal
root: /
permalink: /:year/:month/:day/:title/
category_dir: categories

# Analytics
google_universal_analytics: UA-64916447-1
google_universal_analytics_cookiedomain: auto

# Build settings
markdown: kramdown

linkpost:
  marker: →
  marker_position: after
posts:
  marker: false
  marker_position: before